disabled_rules: # rule identifiers to exclude from running
  - notification_center_detachment
  - trailing_whitespace
  - private_over_fileprivate
  - trailing_closure
opt_in_rules: # some rules are only opt-in
  - attributes
  - closure_end_indentation
  - closure_spacing
  - contains_over_first_not_nil
  - empty_string
  - explicit_init
  - first_where
  - implicit_return
  - joined_default_parameter
  - literal_expression_end_indentation
  - operator_usage_whitespace

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - vendor
  - ProjectTemplates
  - UI/Views/BodyViews
  - PhotoPicker

comma: error
force_cast: warning
force_try: warning
return_arrow_whitespace: error

line_length:
  warning: 150
  error: 200
type_body_length:
  warning: 300
  error: 400
cyclomatic_complexity:
  ignores_case_statements: true
file_length:
  warning: 500
  error: 1000
function_body_length:
  warning: 80
  error: 100
large_tuple:
  warning: 3
  error: 5
identifier_name:
  excluded: # excluded via string array
    - x
    - y
    - z
    - id
warning_threshold: 50
reporter: "xcode"
